trigger:
- main  # or your default branch

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR_AZURE_SERVICE_CONNECTION>'
    appType: 'webApp'
    appName: 'MATH_REPO'
    package: '$(System.DefaultWorkingDirectory)'
